# Generated by Django 3.2.6 on 2022-05-29 18:03

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import scraping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='shahar')),
                ('slug', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'shahar',
                'verbose_name_plural': 'shaharlar',
            },
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestap', models.DateField(auto_now_add=True)),
                ('data', jsonfield.fields.JSONField()),
            ],
            options={
                'verbose_name_plural': 'Errors',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='dasturlash tili')),
                ('slug', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'dasturlash tili',
                'verbose_name_plural': 'dasturlash tillari',
            },
        ),
        migrations.CreateModel(
            name='Vakation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='url')),
                ('title', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('Rezume', models.BooleanField(default=False)),
                ('timestap', models.DateField(auto_now_add=True, null=True)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.city')),
                ('language', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.language')),
            ],
            options={
                'ordering': ['-timestap'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('profession', models.CharField(max_length=128)),
                ('phone_number', models.CharField(default='+998', max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.CharField(max_length=24)),
                ('experience', models.TextField()),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('about_meu', models.TextField()),
                ('telegram_link', models.CharField(blank=True, max_length=128)),
                ('linked', models.CharField(blank=True, max_length=128)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.city')),
                ('language', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.language')),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(default=scraping.models.default_urls)),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.city')),
                ('language', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scraping.language')),
            ],
            options={
                'verbose_name_plural': 'Urls',
                'unique_together': {('city', 'language')},
            },
        ),
    ]
