# Generated by Django 3.2.6 on 2022-05-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='adress',
            field=models.CharField(max_length=128),
        ),
    ]
