# Generated by Django 3.2.6 on 2022-07-31 17:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakation',
            name='title',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True),
        ),
    ]
