# Generated by Django 3.2.6 on 2022-05-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_alter_resume_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='adress',
        ),
    ]
