# Generated by Django 3.2.6 on 2022-05-31 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_resume_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vakation',
            name='company',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vakation',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
