# Generated by Django 3.2.6 on 2022-06-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_auto_20220601_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='resume',
            name='adress',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='resume',
            name='linked',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone_number',
            field=models.CharField(default='+998', max_length=256),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profession',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='resume',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
