# Generated by Django 3.2.6 on 2022-06-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0011_alter_vakation_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Ishlar', 'verbose_name_plural': 'Ishlar'},
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Ishlar'),
        ),
    ]
