# Generated by Django 3.2.6 on 2022-06-09 10:15

from django.db import migrations, models
import scraping.validators


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0012_auto_20220606_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='', validators=[scraping.validators.validate_file_size]),
        ),
    ]
