# Generated by Django 3.2.6 on 2022-06-02 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0007_auto_20220601_0118'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='resume_check',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scraping.resume'),
            preserve_default=False,
        ),
    ]
