# Generated by Django 3.2.6 on 2022-06-02 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_resume_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='resume_check',
        ),
    ]
